services:
  # 前端服务 - Vue.js 应用
  frontend:
    build: ./daily-web
    container_name: daily-web
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - daily-app-network

  # 后端服务 - Node.js/Express 应用
  backend:
    build: ./daily-server
    container_name: daily-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:Bing2003@8.155.40.179:27017/daily_app?authSource=admin
      - PORT=3000
    volumes:
      - ./daily-server/uploads:/app/uploads
    networks:
      - daily-app-network

# 网络
networks:
  daily-app-network:
    driver: bridge
